version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.5.1
        env:
          - MIX_ENV=test
      - image: circleci/postgres:latest
        env:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=Unseen2015

    working_directory: ~/doax3
    steps:
      - checkout
      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix deps.get
      - run: mix ecto.create
      - run: mix test
notify:
  webhooks:
    - url: https://discordapp.com/api/webhooks/359918967139336192/q4a4OCRqnu4k4GaSE1rLcgvcT08_SPo0PDgyPu3Eeg4U6fg0wihBTsQxBFELStor6n6R/circle
