version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.5.1
        env:
          - MIX_ENV=test
      - image: circleci/postgres:latest
        env:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=Unseen2015

    working_directory: ~/doax3
    steps:
      - checkout
      - run: mix deps.get
      - run: mix ecto.create
      - run: mix test
